### ISSUE TITLE
Run migration error 

### ISSUE THREAD

**Issue by LeoMoshko** [Niiph/SyliusProductLabelPlugin#21]
When I run the migration generation command (bin/console doctrine:migrations:diff), I have the following error:

`  Cannot load migrations from "/app/vendor/niiph/sylius-common/migrations" because it is not a valid directory`

Temporarily solve - create the folder from this path.

**Comment by Niiph** [comment]
@LeoMoshko thanks. I've added missing directory in `niiph/sylius-common`
